on:
  push:
    paths:
      - 'ziffer_raw/**'  

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
      - name: push changes to remote
        run: |
           git config --global user.name "user mane"
           git config --global user.email "user email"
           git add ./ 
           git add ./a_output_actual/
           git add ./b_output_historic/
           git add ./ziffer_resize/
           git commit -m "auto run"
           git push